# Generated by Django 5.0.4 on 2024-05-22 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinhvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.FloatField()),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinhvien.monhoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinhvien.sinhvien')),
            ],
        ),
    ]
